name: Publish

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: "hstreamdb/hstream"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: publish local java-toolkit
        working-directory: ./java-toolkit
        run: ./gradlew publishToMavenLocal -PdisableSigning --info --refresh-dependencies

      - name: build images
        run: |
          export CONNECTOR_IMAGE_VERSION=${GITHUB_REF#refs/*/}
          make build_images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: |
          export CONNECTOR_IMAGE_VERSION=${GITHUB_REF#refs/*/}
          ./scripts/publish_images.sh conf/ci_publish_images

